[exporters]
# Add your target hosts for node_exporter here
# example_host1 ansible_host=192.168.1.10

[prometheus]
localhost ansible_connection=local

[grafana]
localhost ansible_connection=local

[elk]
# localhost ansible_connection=local

[alertmanager]
localhost ansible_connection=local
